### ISSUE TITLE
Footer class too thick when used in Grid

### ISSUE THREAD

**Issue by mermelmadness** [th3jesta/ha-lcars#34]
![image](https://user-images.githubusercontent.com/38080873/211661062-67a3e7bc-87f6-4df6-b0ea-77a906ab7574.png)
Thicc Boi
```
type: markdown
content: '# Appliances'
theme: LCARS Default
card_mod:
  class: footer-right
```

**Comment by csanner** [comment]
if you set "square: false" what do you get?

**Comment by mermelmadness** [comment]
No change

**Comment by th3jesta** [comment]
Here's what's happening here:
The markdown card, because it's in the same row as larger card, is being forced to unnaturally match the height of its larger neighbor, thus stretching it's bottom border beyond its defined `10px`. I assume this happens before it takes the size of the text into account, which could explain the little bit of overhang. How to fix this? I'm not sure, and I'm not sure it can be fixed as this is farther and farther into actual Home Assistant responsive behavior vs. simple CSS styling. (wait, nothing in this theme is simple) I'll be digging into this, but don't expect a fix soon.

**Comment by th3jesta** [comment]
In the meantime, you could try adding a blank line above your title in the Markdown, as described in the Tips and tricks section:
```
## &nbsp;
## Appliances
```
...adding or removing `#` to adjust the size of the blank line(s).
