### ISSUE TITLE
Text/font 'thickness/boldness' issue and/or modification

### ISSUE THREAD

**Issue by derekisastro** [th3jesta/ha-lcars#54]
Hi,

Loving the LCARS theme. The only main issue I have is that on many screens the font is a little too ‘thin’, if that makes sense. It actually makes the font quite difficult to read. Is there a way to modify the font ‘heaviness’ (like bolding or simply making the letters/numbers a little ‘thicker’)?

If I do choose to create my own custom theme to do this, how do I go about it? I can see how I can create my own themes color scheme at the bottom of the lcars.yaml file but there is no mention of font in that section.

Any help is appreciated, thanks.

![lcars font](https://user-images.githubusercontent.com/36499125/218530716-9f7a86d8-715f-49cf-a68a-90780e289ac4.png)

**Comment by th3jesta** [comment]
Hi there!
To directly address your question, you can technically import any font you want in the Resources page. I just used the font that was chosen for thelcars.com. If you want to play with the font weight, you can [go here](https://fonts.google.com/specimen/Antonio/tester?query=antonio) and find the weight that suits your needs, and just copy the URL or the number values that you have chosen into your existing URL you put in HA.
To come at this another way, the text in your image above looks garbled and incorrect. I'd like to try and understand why, because even at a low resolution or zoom level, it shouldn't look like that. Can you please provide the following?
* Device
* OS
* Device resolution
* Browser or app
* Zoom level in browser
I may have more questions later, but that should get us started./

**Comment by derekisastro** [comment]
Sounds great, thanks!

To answer your questions, and provided additional information. This 'look' only occurs on my work monitor at the moment. It's a Dell laptop, a Latitude something ... it has a second monitor attached, an Asus monitor.

It is running Windows 10, it is 1920 x 1080 resolution, displayed on Google Chrome. I believe my zoom level should be default/standard ... yep, it appears to be at 100%.

It is clear it does not do it on all my displays but I figured a slightly heavier font would help for any time on any display when it might happen. Thanks for your help.
