### ISSUE TITLE
Button text overflows

### ISSUE THREAD

**Issue by 3VAbdAVE** [th3jesta/ha-lcars#55]
Great theme, appreciate the instructions for custom colors. I've a problem with overflowing text on buttons.
I tried adding a "word-wrap: break-word;" property to the classes, but it didn't have an effect. Also tried it in a card_mod style, but it appears to be beyond my CSS knowledge.

![image](https://user-images.githubusercontent.com/112563233/219549844-572f84a5-7986-44f1-95c7-8ec5510b2046.png)

**Comment by th3jesta** [comment]
Yikes, that's a tight layout. 
So, the way the CSS is constructed, word-wrapping is going to be a major headache and probably won't produce useable results. I have two recommendations, easiest first:
1. Change the button text to something that will fit, such as BAR VIRTUAL instead of BAR VIRTUAL BUTTON or maybe just BAR.
2. Reduce the font size instead of wrapping it.
Unless it's just not feasible for you, I think changing the button text is the best route and what I have done personally. I think abbreviations would even be in keeping with LCARS style, like 'Ops' instead of 'Operations.'

**Comment by th3jesta** [comment]
I was able to make the buttons shorter by adding the `max-height: 40px;` property to the `ha-card.button-bullet` and reducing the `min-height` property to <= `max-height`.

**Comment by 3VAbdAVE** [comment]
That's the standard Media Player card (type: media-control), no changes to it.
