### ISSUE TITLE
Middle Class Padding

### ISSUE THREAD

**Issue by CmdreIsaacHull** [th3jesta/ha-lcars#57]
I've been going through my cards and adding some gaps to the middle cards, since these are the only classes where there are no gaps between the solid border bars and the content. I thought it might be cool to add that to the overall theme for everyone. 

I'm not sure where exactly these lines would go in the .yaml, so I am posting here instead of a pull request. 

```
#Middle
    ha-card {
      padding-left: 6px !important;
    }

#Middle Right
    ha-card {
      padding-right: 6px !important;
    }
```

![image](https://user-images.githubusercontent.com/93444427/224374331-269bc5f0-6abc-40f2-9a24-555be10c143e.png)

I think it looks so much better than stock.

**Comment by thedjelectron** [comment]
These gaps could also be useful when using the header or footer classes on a normal card instead of a markdown card.

I went through and looked at the footers, specifically, and found that adding these lines cleaned up the footer:

```
ha-card.footer {
  background: var(--ha-card-background) !important;
}
ha-card {
  padding: 0px 0px 6px 6px !important;
}
element.style {
  border-radius: 40px;
}
```

![image](https://user-images.githubusercontent.com/93444427/224398795-237d8a38-dc56-4b69-8a27-f6036a6c8a05.png)


I still couldn't figure out how to control the inner radius though.

**Comment by thedjelectron** [comment]
That element.style gives the 40px radius to the corners of the picutre, but that element must have reset while I was messing with the console before I took the screenshot.

**Comment by th3jesta** [comment]
Shipping in 2.0
