### ISSUE TITLE
Red Color from Cards Does Not Appear

### ISSUE THREAD

**Issue by mermelmadness** [th3jesta/ha-lcars#8]
Sorry to open another issue, but some cards don't display all colors using this theme:

![image](https://user-images.githubusercontent.com/38080873/208334410-7903724c-9ea3-491a-8c08-bcbeb6ae2908.png)
![image](https://user-images.githubusercontent.com/38080873/208334413-e0c54cc5-21ef-4fdf-a034-0739126912ad.png)

**Comment by th3jesta** [comment]
I would try applying the `button-large` or `button-small` classes to he cards.

**Comment by mermelmadness** [comment]
No effect....as they're not buttons.

**Comment by th3jesta** [comment]
The class names only correspond to their intended use. They will work on any card. Please share the full yaml for your card, and we'll go from there.

**Comment by mermelmadness** [comment]
Here's my initial code.  Where should the `class: button-small` go?

`type: grid
cards:
  - type: gauge
    entity: sensor.cpu_temp_f
    min: 35
    max: 85
    needle: true
    severity:
      green: 0
      yellow: 65
      red: 75
    name: CPU Temp
    theme: LCARS Classic
  - type: gauge
    entity: sensor.processor_use
    min: 0
    max: 100
    name: CPU Usage
    severity:
      green: 0
      yellow: 75
      red: 90
    needle: true
    theme: LCARS Classic
  - type: gauge
    entity: sensor.memory_use_percent
    min: 0
    max: 100
    name: Memory Usage
    severity:
      green: 0
      yellow: 75
      red: 90
    needle: true
    theme: LCARS Classic
  - type: gauge
    entity: sensor.disk_use_percent
    min: 0
    max: 100
    severity:
      green: 0
      yellow: 75
      red: 90
    name: Disk Usage
    needle: true
    theme: LCARS Classic
columns: 2
square: false`

**Comment by th3jesta** [comment]
First, rather than setting the theme on the cards themselves, you should set them as described in the instructions, that way you'll get the theme applied to the sidebar and header bar, as well as the font! Then you can add classes to the cards individually. So where you have `theme: LCARS CLASSIC`, instead you would have the following:
```
card_mod:
  class: button-small
```
...making sure that your indentations are correct (typing this from mobile on vacation). This theme incorporates more advanced usage of the card-mod integration that applies the theme to all of Home Assistant instead of just the individual cards. Thanks for your patience. This is helping me understand how need to shore up the documentation!

**Comment by mermelmadness** [comment]
I typically don't like to use YAML unless the Visual Editor isn't supported.  I don't see a way to set the `card_mod` from the Visual Editor, so is it best for me to make the card using the GUI first then add
```card_mod:
  class: button-small
if the colors don't work right?

Also, making a new Dashboard using the LCARS theme does not set the sidebar as pictured in the Github, unless I'm doing it wrong.
![image](https://user-images.githubusercontent.com/38080873/208339983-4db3bc64-bbaa-40ac-99db-20a41c507980.png)

**Comment by mermelmadness** [comment]
> (typing this from mobile on vacation)

Dude, this can definitely wait.  Enjoy your time and the holidays and we can come back to this when you're back home.

**Comment by th3jesta** [comment]
Thanks! We'll definitely get you set up with it when I get back. It's worth it!

**Comment by mermelmadness** [comment]
Let me know when you get back.  I'm ready when you are.

**Comment by th3jesta** [comment]
Driving back tomorrow. Look for a reply tomorrow evening or the day after!

**Comment by th3jesta** [comment]
Okay, back from vacation. So much easier to make sense of all of this from my PC as opposed to my phone.
First, please confirm for me that you have enabled the theme globally via one of the options indicated [here](https://github.com/th3jesta/ha-lcars#enable-theme). This will apply the theme to the sidebar and the header bar, and the font everywhere it can be set. 
Once you've done that, we'll move on to the dashboard. Since the theme was enabled globally per the previous paragraph, we do not need to set the theme on the individual cards. All we need to do is add the classes to each card, depending on the style you want to set. Add a card to the dashboard, and then edit the card. You'll see a link to edit the YAML for that card (easier to do this than the YAML for the entire dashboard). This is example YAML for a button card:
```
show_name: true
show_icon: true
type: button
tap_action:
  action: toggle
entity: switch.speakers
show_state: true
icon: mdi:speaker-multiple
card_mod:
  class: button-bullet
```
The relevant portion is:
```
card_mod:
  class: button-bullet
```
Lemme know how this goes.

**Comment by mermelmadness** [comment]
So that seems to have worked now.  Red color still missing from gauge cards.  The picture is my existing dashboard copied to a new layout.  I don't have any button cards.  How do I get that wrap-around border?
![image](https://user-images.githubusercontent.com/38080873/209894969-9002480c-4368-49e5-a936-63c0fe3fe76e.png)

**Comment by th3jesta** [comment]
Okay, a few things:

- You've selected the LCARS Classic theme which has no red color in it. Red is included in the Default theme.
- Please review the portion of the documentation about the classes; this explains how to use them and what they do, such as the "wrap around" border you mentioned. I suspect you were referencing the top and lower bars above and below a section of cards. I'm also going to expand the documentation of the classes to make it easier to understand; I realize it's lacking.
- Your sidebar still doesn't look right to me, as it's missing the outer radius in the top left. I'd like to investigate this further, but first, I would recommend ensuring you have the latest release. Can you send a screenshot of the expanded sidebar, please?

**Comment by th3jesta** [comment]
I have updated the classes documentation add more clarity. Please let me know if you find any deficiencies in it.

**Comment by mermelmadness** [comment]
First, the Default theme still does not show any red in my gauge cards.
![image](https://user-images.githubusercontent.com/38080873/210183686-ab40c34c-a697-44ad-802b-028e0329139c.png)

Second, I don't really understand how classes work or where they belong in the YAML code configuration.  Would it be possible to post screenshots of formatted cards and their corresponding YAML code as examples?

**Comment by th3jesta** [comment]
Sure, but before that, in your screenshot, where are you expecting red? I see a lot of red, and thought that's where you were expecting it. I'm not familiar with the gauge cards as I've never used them. 

Here's an example of how to get to the YAML for a Markdown card and apply the `header` class to it:
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/38670315/210184466-0e04ed2a-43e0-4660-b62d-43736ed27ba4.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/38670315/210184483-524537d1-3e79-46ba-a446-a27581f024e4.png">
<img width="356" alt="image" src="https://user-images.githubusercontent.com/38670315/210184508-75c4a0c4-c9ae-48c1-ac97-96c116ae1f0d.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/38670315/210184518-db0b7774-9061-4253-aabb-ba1e4e9df053.png">
<img width="785" alt="image" src="https://user-images.githubusercontent.com/38670315/210184606-ff6a190f-2145-442c-9736-48d0292869f9.png">
<img width="802" alt="image" src="https://user-images.githubusercontent.com/38670315/210184623-5670b6ae-3a54-4118-acb2-3202160de1ff.png">
<img width="488" alt="image" src="https://user-images.githubusercontent.com/38670315/210184632-97ee7d0b-ca7e-47df-89fa-d63b1b40d8d4.png">

**Comment by th3jesta** [comment]
Oh, I see, gold in the gauge should be red. My apologies for the goose chase. I'll have to work on this to fix the colors of the gauges themselves.

**Comment by mermelmadness** [comment]
Ok, got the header working, just gotta finagle the layout a bit.  For the gauges, it goes green, yellow, red (in most cases).
![image](https://user-images.githubusercontent.com/38080873/210184806-4b41faf7-4eda-4b7a-a06b-c04fb957b6db.png)

**Comment by mermelmadness** [comment]
Sort of works...
![image](https://user-images.githubusercontent.com/38080873/210184858-1bbaad38-887d-4b16-af8d-15033d7e4a99.png)

**Comment by th3jesta** [comment]
Ah, if you add `# ` in front of your text, that makes the text size H1 (largest size) as in my screenshot. Check out the Markdown card reference in HA documentation to learn how to format text in Markdown cards. 

I figured out the red issue. It was a missing `#` on the color code defined in the theme, causing it to render transparent. (facepalm) Pushing the fix now and packaging it into a hotfix release.

**Comment by th3jesta** [comment]
Color is fixed in Release HA-LCARS-1.7.1

Now, regarding your header and sidebar, I'm beginning to suspect you may have another add-on that's modifying either one or both, since the custom styles appear to be applying everywhere but there. Do you have any kind of custom header or sidebar, or anything else that might conflict?

Also, at the bottom of the readme, I added a link to the new Discord server I set up for HA-LCARS.

**Comment by mermelmadness** [comment]
Joined the Discord.  Ping me @mermel

**Comment by th3jesta** [comment]
Closing this since the original issue has (finally) been addressed. Will continue support for sidebar and header in Discord.
